name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "💌 Thanks for raising the issue. We appreciate your keen eye and look forward to resolving it together."
        pr-message: "🌟 Welcome aboard! Excited to see your pull request. Thanks for making the contribution."
